version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - sudo npm install
  build:
    commands:
      - sudo npm run build

artifacts:
  files:
    - "**/*"
  base-directory: client/build
